name: Domain Deployment Template

on:
  workflow_call:
    inputs:
      prefix:
        description: The app prefix
        required: true
        type: string
      domain_name:
        description: The main URL
        required: true
        type: string
      deployment_bucket:
        description: The S3 bucket used for deployments
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Set environment variables
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Deploy the domain
        working-directory: server/domain
        run: aws cloudformation deploy --template-file template.yml --stack-name ${{ inputs.prefix }}-domain --parameter-overrides DomainName=${{ inputs.domain_name }} DeploymentBucket=${{ inputs.deployment_bucket }} --capabilities CAPABILITY_IAM
