name: Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  database:
    uses: ./.github/workflows/_database.deploy.yml
    with:
      env_name: prod
    secrets: inherit

  socket:
    needs: database
    uses: ./.github/workflows/_socket.deploy.yml
    with:
      env_name: prod
      stage_name: Stage
      wss_url: wss.tictacgo.xyz
    secrets: inherit

  website:
    needs: socket
    uses: ./.github/workflows/_website.deploy.yml
    with:
      env_name: prod
      url: www.tictacgo.xyz
      cnames: www.tictacgo.xyz,tictacgo.xyz
    secrets: inherit
