name: Production Deployment

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Set environment variables
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Deploy the database
        run: |
          cd $GITHUB_WORKSPACE/server/database
          npm run deploy

      - name: Deploy the socket service
        run: |
          cd $GITHUB_WORKSPACE/server/socket
          npm run deploy

      - name: Deploy the website
        run: |
          cd $GITHUB_WORKSPACE/client
          npm install -g @angular/cli
          npm run deploy
