name: Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  domain:
    uses: ./.github/workflows/_domain.deploy.yml
    with:
      prefix: ttg
      domain_name: tictacgo.xyz
      deployment_bucket: deployments.tictacgo.xyz
    secrets: inherit

  database:
    uses: ./.github/workflows/_database.deploy.yml
    with:
      prefix: ttg
      env_name: prod
    secrets: inherit

  socket:
    needs: [domain, database]
    uses: ./.github/workflows/_socket.deploy.yml
    with:
      prefix: ttg
      env_name: prod
      stage_name: Stage
      wss_url: wss.tictacgo.xyz
      deployment_bucket: deployments.tictacgo.xyz
    secrets: inherit

  website:
    needs: socket
    uses: ./.github/workflows/_website.deploy.yml
    with:
      prefix: ttg
      env_name: prod
      url: www.tictacgo.xyz
      cnames: www.tictacgo.xyz,tictacgo.xyz
    secrets: inherit
