name: Sandbox Deployment

on:
  workflow_dispatch:

jobs:
  database:
    uses: ./.github/workflows/_database.deploy.yml
    with:
      env_name: sb
    secrets: inherit

  socket:
    needs: database
    uses: ./.github/workflows/_socket.deploy.yml
    with:
      env_name: sb
      stage_name: Stage
      wss_url: sb-wss.tictacgo.xyz
    secrets: inherit

  website:
    needs: socket
    uses: ./.github/workflows/_website.deploy.yml
    with:
      env_name: sb
      url: sb.tictacgo.xyz
      cnames: sb.tictacgo.xyz
    secrets: inherit
